---
################ NLB NODE ################

# The current application instance name.
name: "worker_queue"

################ LOGGER ################
logger:
  console_logger:
    enabled: true # always true
  run_log_file:
    enabled: true # always true
    path: "log/run.log"
    # Default maxsize = 10MB.
    # Max size in bytes of the logfile, if the size is exceeded then a new file is created.
    maxsize: 10485760
    # Limit the number of files created when the size of the logfile is exceeded.
    maxFiles: 10
  exception_log_file:
    enabled: true # always true
    path: "log/exceptions.log"
    # Default maxsize = 10MB.
    # Max size in bytes of the logfile, if the size is exceeded then a new file is created.
    maxsize: 10485760
    # Limit the number of files created when the size of the logfile is exceeded.
    maxFiles: 10

################ DEBUG ###################

# Set `true` to enable debug mode.
debug_mode: false

################ HTTP ####################

http:
  # set `null` to use PORT environment value. Use 3000 as default if no PORT environment is set.
  # or set to an integer port like 8080
  port: null

################ QUEUE ####################

# job prefix in redis.
job_prefix: "q"

# Set `ture` to enable node cluster mode.
cluster_mode: false

# Set number of CPU cores to be used for cluster.
# If the set number exceeds the max number of system has, it will use the max number instead.
cluster_worker_size: 2

################ Redis ####################
redis_conn:
  port: 6379
  host: "127.0.0.1"
  # see https://github.com/mranney/node_redis#rediscreateclientport-host-options
  options: null


################ Workers ####################

workers:

# ----------- PDF2SWF -----------
  pdf2swf:
    worker_type: pdf2swf
    concurrency_number: 1
    script_path: ./tools/pdf2swf.sh
    win_script_path: ./tools/windows/pdf2swf.bat
    data_path: ./data